### ISSUE TITLE
Not working in IE8 with latest jquery library 1.11 version

### ISSUE THREAD

**Issue by Viveksubramani** [jquery-i18n-properties/jquery-i18n-properties#10]
Languages are not loading in IE when I use jquery 1.11 version

**Comment by adrianfish** [comment]
@Viveksubramani Is IE8 really an issue? Support has now been dropped by Microsoft. I'm closing this one.

https://blogs.msdn.microsoft.com/ie/2014/08/07/stay-up-to-date-with-internet-explorer/
