### ISSUE TITLE
How to force load only language file?

### ISSUE THREAD

**Issue by toni-moreno** [jquery-i18n-properties/jquery-i18n-properties#11]
Hi to all.

When running my loadConfig() function it really is trying to  load two files from de server.

config.properties
config_<LANG>.properties

my config.properties doen't exist , and give me a  404 Not Found error,

There is any way to force only one?  (config_<LANG>.properties) 

this is my code.

```
function loadConfig() {

    $.i18n.properties({
        name:'config', 
        path:'properties/', 
        language:'',
        cache: true,
        mode:'both',
        callback: function(){
            console.log('properties loaded');
        }
    });
}
```

**Comment by adrianfish** [comment]
This doesn't make any sense. config_ is not a valid Java properties file name as '_' is not a language string.
