### ISSUE TITLE
synchronous ajax request

### ISSUE THREAD

**Issue by rileytg** [jquery-i18n-properties/jquery-i18n-properties#14]
```
$.ajax({
      url: indexFileUrl,
      async: false,
      cache: false,
      success: function (data, status) {
          languages = data.languages;
      }
    });
```

why not async?

**Comment by prabintp** [comment]
showing warning in browser console since not async
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

**Comment by gregpettit** [comment]
Yup, spotted. I understand the logic of making the calls synchronous (you need your language before you try to use it or you're at risk of 'undefined' hell) but most of us could just call some sort of initialization method in the async callback if we want to delay using the language.

**Comment by adrianfish** [comment]
@gregpettit Fixed, take a look at the docs for details on how do do async.
