### ISSUE TITLE
Why FF throws error about jquery-i18n-properties .properties content.

### ISSUE THREAD

**Issue by manueljordan** [jquery-i18n-properties/jquery-i18n-properties#24]
Hello 

I have the following structure for a Spring Web App

![structure](https://cloud.githubusercontent.com/assets/2552795/12093904/95484934-b2d3-11e5-85cc-be65e55b36c5.png)

To create a .properties files in many languages I use: [essiembre/eclipse-rbe](https://github.com/essiembre/eclipse-rbe)

For example `message.properties` contains:

```
id = Campo ID no puede estar vacio.
```

and `message_en_US.properties` contains:

```
#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)

id = Field ID can't be empty.
```

My code about jquery-i18n-properties is:

```
jQuery.i18n.properties({
				name: 'message',
				path: '../resources/jquery.i18n.properties/messages/',
				mode: 'both',

				callback: function() {
					console.log(jQuery.i18n.prop('id'));
				}
			});
```

When I execute the code on Opera and Chrome all work fine.

But just in Firefox 43.0.2 (Mac) I can see the following:

![syntaxerror](https://cloud.githubusercontent.com/assets/2552795/12094053/77547fa0-b2d4-11e5-98bc-7015f30bc4fb.png)

If I do click for each error syntax in the right part (blue text) I can see the following respectively.

```
id = Campo ID no puede estar vacio.
```

And

```
#Generated by ResourceBundle Editor (http://essiembre.github.io/eclipse-rbe/)

id = Field ID can't be empty.
```

I don't know why that error is arising

Some ideas?

Thanks

**Comment by adrianfish** [comment]
Incorrect mimetype?

**Comment by adrianfish** [comment]
The workaround from this, in Tomcat at least, is to add ...

<mime-mapping>
        <extension>properties</extension>
        <mime-type>text/plain</mime-type>
</mime-mapping>

... to conf/web.xml

**Comment by manueljordan** [comment]
Hi @adrianfish 

I have located the `web.xml` on TOMCAT_HOME/conf location.

But where exactly and how I should add your 

```
properties
text/plain
```

Thanks!

**Comment by adrianfish** [comment]
Search the file for 'mime-mapping' and you'll find where to add it. I'm using Tomcat 7.
