### ISSUE TITLE
async true version release.

### ISSUE THREAD

**Issue by dongully** [jquery-i18n-properties/jquery-i18n-properties#33]
I have same problem with this post.
https://github.com/jquery-i18n-properties/jquery-i18n-properties/issues/25

Trying async: true settings, but haven't clear warning.
And I inspected the code in latest 1.2.0 version.
But, in ver.1.2.0, settings.async seems to be ignored.

** ver.1.2.0 **
<pre>
function loadAndParseFile(filename, settings) {
	$.ajax({
        url:        filename,
        async:      false,
        cache:		settings.cache,
        contentType:'text/plain;charset='+ settings.encoding,
        dataType:   'text',
        success:    function(data, status) {
        				parseData(data, settings.mode); 
					}
    });
}
</pre>

** latest code **
<pre>
function loadAndParseFile(filename, settings) {
    $.ajax({
        url: filename,
        async: settings.async,
        cache: settings.cache,
        dataType: 'text',
        success: function (data, status) {
        parseData(data, settings.mode);
            callbackIfComplete(settings);
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log('Failed to download or parse ' + filename);
            callbackIfComplete(settings);
        }
    });
}
</pre>

When do you release async true version.

**Comment by adrianfish** [comment]
You supply the async flag in the settings object. That way it's all under the control of the calling code.

**Comment by dongully** [comment]
yes, using that way, I cat avoid warning 'in latestcode'.
but 'in latest release(ver.1.2.0)', can't avoid.
because loadAndParseFile method is older.
I'm using webjar, so please release latestcode.

**Comment by dongully** [comment]
Using latest release(ver.1.2.2), I can avoid async problem.
thank you.
