### ISSUE TITLE
Using synchronous loading of properties with jquery.i18n.properties in deferred scripts fails in Firefox

### ISSUE THREAD

**Issue by rajsite** [jquery-i18n-properties/jquery-i18n-properties#43]
If one uses a script with the defer attribute to invoke synchronous property loading with jquery-i18n-properties then it may fail in Firefox.

Ex:

<script defer src="jquery.js"></script>

<script defer src="jquery.i18.properties.js"></script>

<script defer src="support_file_that_invokes_jquery_i18n_and_creates_helper_functions.js"></script>

<script defer src="file_uses_helper_functions.1.js"></script>

<script defer src="file_uses_helper_functions.2.js"></script>

<script defer src="file_uses_helper_functions.n.js"></script>

This may be fixed in future versions of Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1212696#c33

Not sure if switching to the async configuration when using deferred instead of a sync will fix the behavior but I think it might.

**Comment by adrianfish** [comment]
I don't think this is something that can be fixed in the plugin.

**Comment by rajsite** [comment]
> Not sure if switching to the async configuration when using deferred instead of a sync will fix the behavior but I think it might.

Switching to async: true when using this plugin fixed the problem for us when loading the script as defer. 

Agree that other than trying to detect and warn there is not much the plugin could do. Thanks for taking the time to look at the issue.
