### ISSUE TITLE
Memory Leak in IE11

### ISSUE THREAD

**Issue by sjulescu** [jquery-i18n-properties/jquery-i18n-properties#48]
The variable: "var cbSplit; " declared as global variable is creating a memory leak in IE11.
The page where the library is used will always leak in IE11 because the  IE garbage collector will not garbage it.

In order to confirm the leak I added a temporary function cleancbSplit to nullify the cbSplit variable and the memory leak was gone.

var cbSplit;
// avoid running twice, which would break `cbSplit._nativeSplit`'s reference to the native `split`
if (!cbSplit) {  
  cbSplit = function(str, separator, limit) {
  .....................
  cbSplit._nativeSplit = String.prototype.split;

```
window.cleancbSplit = function() {
    cbSplit = null;
}
```

}

**Comment by adrianfish** [comment]
Fixed in master.
