### ISSUE TITLE
Some console.log in minified code.

### ISSUE THREAD

**Issue by juanjmerono** [jquery-i18n-properties/jquery-i18n-properties#59]
I've found some debug messages "console.log" in the minified version.

 console.log("HERE1");

**Comment by adrianfish** [comment]
I forgot about the min version :)

**Comment by juanjmerono** [comment]
I've been testing with roster2 and it was also looking for a missing json file.
![error](https://cloud.githubusercontent.com/assets/8570908/24552026/317e8b1e-1625-11e7-8b97-7aec7fcac868.jpg)

Is the behaviour changed from 1.2.2 to 1.2.3 ?

**Comment by adrianfish** [comment]
Yep, I've got rid of the languages file business. It was just causing confusion. I need to update Roster2. If you want to drop me  a PR, that'd be great :)
