### ISSUE TITLE
Android Chrome browser and WebView can fail to load

### ISSUE THREAD

**Issue by rajsite** [jquery-i18n-properties/jquery-i18n-properties#65]
Sometimes in Chrome Browser and Chrome WebView for Android the navigator.languages property exists and is an empty array. This causes the following line to error: https://github.com/jquery-i18n-properties/jquery-i18n-properties/blob/master/jquery.i18n.properties.js#L429

When trying to perform toLowerCase on undefined.

Android 7.1.2
Chrome 57.0.2987.132

**Comment by aim12340** [comment]
I'm seeing similar problem on windows 7 with chrome 57.0.2987.133 (from the useragent)
It seems to be down to language detection, i cant say if ti's an empty array or not.
