### ISSUE TITLE
if any key is not found in properties file it should not throw error. Exception should be handled.

### ISSUE THREAD

**Issue by jitchakraborty** [jquery-i18n-properties/jquery-i18n-properties#72]
if any key is not found in properties file it should not throw error. Exception should be handled by checking 'value' before accessing this object in the plugin.

from line no 237 the below changes is required to handle the exception in jquery.i18n.properties.js

if (value && value.length === 0) {
            return "";
        }
        if (value && value.length == 1 && typeof(value[0]) == "string") {
            return value[0];
        }

        var str = "";
        var len=0;
        if(value){
        	len = value.length;
        }
        for (i = 0, j = len; i < j; i++) {

**Comment by jitchakraborty** [comment]
Please check this part of the source code

**Comment by obxyann** [comment]
also when call  $.i18n.prop(key) outside the $.i18n.properties's callback (especially iin async mode) it may throw a value undefined exception! because in
```
$.i18n.prop = function (key /* Add parameters as function arguments as necessary  */) {
    var value = $.i18n.map[key];
    if (value === null) {
```
the $.i18n.map may be empty and value is undefined (not full equal null), maybe consider use below ?

`    if (value == null) {
`

**Comment by adrianfish** [comment]
Fixed in master
