### ISSUE TITLE
Uncaught ReferenceError: settings is not defined

### ISSUE THREAD

**Issue by yuricampolongo** [jquery-i18n-properties/jquery-i18n-properties#90]
Hi!

I put my language properties file under resources/bundle/Messages_**.properties

I imported the plugin:

`<!-- Internacionalização --> <script src="resources/js/jquery.i18n.properties.min.js" type="text/javascript"></script>`

and loaded in my .js file:

`$(document).ready(function() {
    jQuery.i18n.properties({
        name: 'Messages',
        path: 'resources/bundle/',
        mode: 'both',
        language: 'en',
        async: true,
        callback: function() {
            console.info('Iniciando internacionalização');
            $('[data-i18n]').each(function(e) {
                var tagName = $(this).get(0).tagName;
                switch (tagName) {
                    case "A":
                        $(this).html(jQuery.i18n.prop($(this).attr("data-i18n")));
                        break;
                }
            });
        }
    });
});`

but I`m getting the following error:

> jquery.i18n.properties.min.js:9 Uncaught ReferenceError: settings is not defined
> at Object.h.i18n.prop (jquery.i18n.properties.min.js:9)
> at HTMLAnchorElement. (default.js:35)
> at Function.each (jquery.min.js:2)
> at n.fn.init.each (jquery.min.js:2)
> at Object.callback (default.js:31)
> at v (jquery.i18n.properties.min.js:1)
> at n (jquery.i18n.properties.min.js:1)
> at jquery.i18n.properties.min.js:1
> at Object.success (jquery.i18n.properties.min.js:2)
> at i (jquery.min.js:2)

what am I doing wrong?

**Comment by ccsldya** [comment]
oops， I have same issue ; Do not use the min.js,  use jquery.i18n.properties.js, it will work temporary;

**Comment by lighter** [comment]
@ccsldya It's work for me.

**Comment by yuricampolongo** [comment]
@ccsldya it's work for me too.

**Comment by qizf7** [comment]
Thx, it's work..

**Comment by a303732207** [comment]
@ccsldya it's work for me too.
